# -*- coding: utf-8 -*-
"""Sift_descriptor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-aGGbFJsPM4vqqJ5XwBolcTBhNtsOR_
"""

# =====================================================
# IMPORTS
# =====================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt
import math
import random

# =====================================================
# UPLOAD IMAGES
# =====================================================

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

# =====================================================
# LOAD IMAGE
# =====================================================

import cv2

img1 = cv2.imread(
    "img_1 (1).jpeg",
    cv2.IMREAD_GRAYSCALE
)

img2 = cv2.imread(
    "img_2 (1).jpeg",
    cv2.IMREAD_GRAYSCALE
)

print(img1.shape)
print(img2.shape)

# =====================================================
# GLOBAL PARAMETERS
# =====================================================

NUM_OCTAVES = 4

SIGMAS = [
    1.6,
    2.0,
    2.52,
    3.17,
    4.0,
    5.04,
    6.35,
    8.0
]

# =====================================================
# GAUSSIAN PYRAMID
# =====================================================
#
# Purpose:
# Create multiple blurred versions of the image
# at different scales.
#
# Output:
# pyramid[octave][scale]
#
# Example:
#
# Octave 0:
#   sigma = 1.6
#   sigma = 2.0
#   sigma = 2.52
#   ...
#
# Octave 1:
#   same sigmas but on half-sized image
#
# =====================================================

def build_gaussian_pyramid(
    img,
    num_octaves=NUM_OCTAVES,
    sigmas=SIGMAS
):

    # store all octaves
    pyramid = []

    # convert image to float
    current = img.astype(
        np.float32
    )

    # build each octave
    for octave in range(
        num_octaves
    ):

        octave_images = []

        # create blurred images
        for sigma in sigmas:

            blurred = cv2.GaussianBlur(
                current,
                (0, 0),
                sigma
            )

            octave_images.append(
                blurred
            )

        # save current octave
        pyramid.append(
            octave_images
        )

        # downsample image by factor 2
        current = cv2.resize(
            current,
            (
                current.shape[1] // 2,
                current.shape[0] // 2
            ),
            interpolation=cv2.INTER_AREA
        )

    return pyramid

# =====================================================
# TEST GAUSSIAN PYRAMID
# =====================================================

gauss_pyr = build_gaussian_pyramid(
    img1
)

print(
    "Number of Octaves:",
    len(gauss_pyr)
)

for i in range(
    len(gauss_pyr)
):
    print(
        f"Octave {i}:",
        gauss_pyr[i][0].shape
    )

# =====================================================
# DIFFERENCE OF GAUSSIAN PYRAMID
# =====================================================
#
# Purpose:
# Approximate the Laplacian of Gaussian.
#
# Output:
# dog_pyr[octave][dog_level]
#
# =====================================================

def build_dog_pyramid(
    gaussian_pyramid
):

    dog_pyramid = []

    for octave in gaussian_pyramid:

        dog_octave = []

        for i in range(
            len(octave) - 1
        ):

            dog = (
                octave[i + 1]
                -
                octave[i]
            )

            dog_octave.append(
                dog
            )

        dog_pyramid.append(
            dog_octave
        )

    return dog_pyramid

# =====================================================
# TEST DOG PYRAMID
# =====================================================

dog_pyr = build_dog_pyramid(
    gauss_pyr
)

print(
    "Number of Octaves:",
    len(dog_pyr)
)

for i in range(
    len(dog_pyr)
):
    print(
        f"Octave {i}:",
        len(dog_pyr[i])
    )

# visualise one dog image
plt.figure(figsize=(6,6))

plt.imshow(
    dog_pyr[0][0],
    cmap='gray'
)

plt.title(
    "DoG Octave 0 Scale 0"
)

plt.axis('off')

plt.show()

# Commented out IPython magic to ensure Python compatibility.
# =====================================================
# GRADIENT PYRAMID
# =====================================================
#
# Purpose:
# Compute gradient magnitude and orientation
# for every Gaussian image.
#
# Output:
#
# mag_pyr[octave][scale]
# ori_pyr[octave][scale]
#
# =====================================================

def build_gradient_pyramid(
    gaussian_pyramid
):

    mag_pyr = []

    ori_pyr = []

    for octave in gaussian_pyramid:

        octave_mag = []
        octave_ori = []

        for img in octave:

            # Sobel gradients
            dx = cv2.Sobel(
                img,
                cv2.CV_32F,
                1,
                0,
                ksize=3
            )

            dy = cv2.Sobel(
                img,
                cv2.CV_32F,
                0,
                1,
                ksize=3
            )

            # Gradient magnitude
            magnitude = np.sqrt(
                dx**2 + dy**2
            )

            # Gradient orientation
            orientation = (
                np.degrees(
                    np.arctan2(
                        dy,
                        dx
                    )
                )
#                 % 360
            )

            octave_mag.append(
                magnitude
            )

            octave_ori.append(
                orientation
            )

        mag_pyr.append(
            octave_mag
        )

        ori_pyr.append(
            octave_ori
        )

    return mag_pyr, ori_pyr

# =====================================================
# TEST GRADIENT PYRAMID
# =====================================================

mag_pyr, ori_pyr = build_gradient_pyramid(
    gauss_pyr
)

print(
    len(mag_pyr)
)

print(
    len(mag_pyr[0])
)

print(
    len(ori_pyr)
)

print(
    len(ori_pyr[0])
)

#visualise magnitude
plt.figure(figsize=(6,6))

plt.imshow(
    mag_pyr[0][0],
    cmap='gray'
)

plt.title(
    "Gradient Magnitude"
)

plt.axis("off")

plt.show()

#visualise orientation
plt.figure(figsize=(6,6))

plt.imshow(
    ori_pyr[0][0],
    cmap='hsv'
)

plt.title(
    "Gradient Orientation"
)

plt.axis("off")

plt.show()

# =====================================================
# SCALE SPACE EXTREMA DETECTION
# =====================================================
#
# Purpose:
# Find maxima and minima in scale-space.
#
# Output:
#
# (x, y, octave, scale)
#
# =====================================================

def detect_extrema(
    dog_pyramid
):

    keypoints = []

    for octave_idx in range(
        len(dog_pyramid)
    ):

        octave = dog_pyramid[
            octave_idx
        ]

        # skip first and last scale
        for scale_idx in range(
            1,
            len(octave)-1
        ):

            prev_img = octave[
                scale_idx-1
            ]

            curr_img = octave[
                scale_idx
            ]

            next_img = octave[
                scale_idx+1
            ]

            h, w = curr_img.shape

            for y in range(
                1,
                h-1
            ):

                for x in range(
                    1,
                    w-1
                ):

                    value = curr_img[
                        y,
                        x
                    ]

                    neighbors = []

                    # previous scale
                    neighbors.extend(
                        prev_img[
                            y-1:y+2,
                            x-1:x+2
                        ].flatten()
                    )

                    # current scale
                    neighbors.extend(
                        curr_img[
                            y-1:y+2,
                            x-1:x+2
                        ].flatten()
                    )

                    # next scale
                    neighbors.extend(
                        next_img[
                            y-1:y+2,
                            x-1:x+2
                        ].flatten()
                    )

                    neighbors.remove(
                        value
                    )

                    if (
                        value > max(neighbors)
                        or
                        value < min(neighbors)
                    ):

                        keypoints.append(
                            (
                                x,
                                y,
                                octave_idx,
                                scale_idx
                            )
                        )

    return keypoints

# =====================================================
# TEST EXTREMA DETECTION
# =====================================================

extrema = detect_extrema(
    dog_pyr
)

print(
    "Extrema Found:",
    len(extrema)
)

# =====================================================
# CONTRAST FILTER
# =====================================================
#
# Remove weak extrema.
#
# =====================================================

def contrast_filter(
    extrema,
    dog_pyramid,
    threshold=1.0
):

    filtered = []

    for x, y, octave, scale in extrema:

        value = abs(
            dog_pyramid[octave][scale][y, x]
        )

        if value > threshold:

            filtered.append(
                (
                    x,
                    y,
                    octave,
                    scale
                )
            )

    return filtered

contrast_pts = contrast_filter(
    extrema,
    dog_pyr
)

print(
    "After Contrast Filter:",
    len(contrast_pts)
)

# =====================================================
# EDGE FILTER
# =====================================================
#
# Remove edge responses using Hessian matrix.
#
# =====================================================

def edge_filter(
    keypoints,
    dog_pyramid,
    r=10
):

    filtered = []

    for x, y, octave, scale in keypoints:

        img = dog_pyramid[octave][scale]

        if (
            x < 1
            or y < 1
            or x >= img.shape[1]-1
            or y >= img.shape[0]-1
        ):
            continue

        Dxx = (
            img[y, x+1]
            +
            img[y, x-1]
            -
            2 * img[y, x]
        )

        Dyy = (
            img[y+1, x]
            +
            img[y-1, x]
            -
            2 * img[y, x]
        )

        Dxy = (
            img[y+1, x+1]
            -
            img[y+1, x-1]
            -
            img[y-1, x+1]
            +
            img[y-1, x-1]
        ) / 4.0

        trace = Dxx + Dyy

        det = (
            Dxx * Dyy
            -
            Dxy * Dxy
        )

        if det <= 0:
            continue

        ratio = (
            trace * trace
        ) / det

        threshold = (
            (r + 1) ** 2
        ) / r

        if ratio < threshold:

            filtered.append(
                (
                    x,
                    y,
                    octave,
                    scale
                )
            )

    return filtered

edge_pts = edge_filter(
    contrast_pts,
    dog_pyr
)

print(
    "After Edge Filter:",
    len(edge_pts)
)

# =====================================================
# NON MAXIMUM SUPPRESSION
# =====================================================

def nms_filter(
    keypoints,
    dog_pyramid,
    radius=5
):

    scored = []

    for x, y, octave, scale in keypoints:

        response = abs(
            dog_pyramid[octave][scale][y, x]
        )

        scored.append(
            (
                response,
                x,
                y,
                octave,
                scale
            )
        )

    scored.sort(
        reverse=True
    )

    selected = []

    for response, x, y, octave, scale in scored:

        keep = True

        for _, sx, sy, so, ss in selected:

            if octave != so:
                continue

            dist = np.sqrt(
                (x - sx)**2
                +
                (y - sy)**2
            )

            if dist < radius:

                keep = False
                break

        if keep:

            selected.append(
                (
                    response,
                    x,
                    y,
                    octave,
                    scale
                )
            )

    result = []

    for _, x, y, octave, scale in selected:

        result.append(
            (
                x,
                y,
                octave,
                scale
            )
        )

    return result

nms_pts = nms_filter(
    edge_pts,
    dog_pyr,
    radius=15
)

print(
    "After NMS:",
    len(nms_pts)
)

# =====================================================
# MULTI ORIENTATION ASSIGNMENT
# =====================================================
#
# Input:
# (x,y,octave,scale)
#
# Output:
# (x,y,octave,scale,orientation)
#
# =====================================================

def assign_orientations_multi(
    keypoints,
    mag_pyr,
    ori_pyr,
    sigmas=SIGMAS
):

    oriented_keypoints = []

    for x, y, octave, scale in keypoints:

        magnitude = mag_pyr[octave][scale]
        orientation = ori_pyr[octave][scale]

        # sigma corresponding to this scale
        sigma = sigmas[scale]

        # radius used by Lowe
        radius = int(round(3 * 1.5 * sigma))

        hist = np.zeros(36)

        h, w = magnitude.shape

        for dy in range(-radius, radius + 1):

            for dx in range(-radius, radius + 1):

                yy = y + dy
                xx = x + dx

                if (
                    yy < 0
                    or yy >= h
                    or xx < 0
                    or xx >= w
                ):
                    continue

                # Gaussian weighting
                weight = np.exp(
                    -(dx*dx + dy*dy)
                    /
                    (2 * (1.5*sigma)**2)
                )

                mag = magnitude[yy, xx]

                ang = orientation[yy, xx]

                bin_idx = int(
                    np.floor(ang / 10)
                ) % 36

                hist[bin_idx] += (
                    weight * mag
                )

        max_peak = np.max(hist)

        # create orientation(s)
        for bin_idx in range(36):

            if hist[bin_idx] >= 0.8 * max_peak:

                angle = (
                    bin_idx + 0.5
                ) * 10

                oriented_keypoints.append(
                    (
                        x,
                        y,
                        octave,
                        scale,
                        angle
                    )
                )

    return oriented_keypoints

oriented_kps = assign_orientations_multi(
    nms_pts,
    mag_pyr,
    ori_pyr
)

print(
    "Keypoints Before Orientation:",
    len(nms_pts)
)

print(
    "Keypoints After Orientation:",
    len(oriented_kps)
)

print(len(nms_pts))
print(len(oriented_kps))

# =====================================================
# TRILINEAR SIFT DESCRIPTOR
# =====================================================
#
# Output:
# 128 dimensional descriptor
#
# 4 x 4 spatial cells
# 8 orientation bins
#
# =====================================================

def generate_descriptors(
    oriented_keypoints,
    mag_pyr,
    ori_pyr
):

    descriptors = []
    valid_keypoints = []

    for x, y, octave, scale, kp_angle in oriented_keypoints:

        mag = mag_pyr[octave][scale]
        ori = ori_pyr[octave][scale]

        h, w = mag.shape

        descriptor = np.zeros(
            (4,4,8),
            dtype=np.float32
        )

        # 16x16 descriptor window
        radius = 8

        angle_rad = np.deg2rad(
            kp_angle
        )

        cos_t = np.cos(
            angle_rad
        )

        sin_t = np.sin(
            angle_rad
        )

        for dy in range(
            -radius,
            radius
        ):

            for dx in range(
                -radius,
                radius
            ):

                yy = y + dy
                xx = x + dx

                if (
                    yy < 0
                    or yy >= h
                    or xx < 0
                    or xx >= w
                ):
                    continue

                # ----------------------------------
                # Rotate coordinates into keypoint frame
                # ----------------------------------

                x_rot = (
                    cos_t * dx
                    +
                    sin_t * dy
                )

                y_rot = (
                    -sin_t * dx
                    +
                    cos_t * dy
                )

                # ----------------------------------
                # Convert to descriptor coordinates
                # ----------------------------------

                col_bin = (
                    x_rot / 4.0
                ) + 1.5

                row_bin = (
                    y_rot / 4.0
                ) + 1.5

                if (
                    row_bin < 0
                    or row_bin >= 4
                    or col_bin < 0
                    or col_bin >= 4
                ):
                    continue

                # ----------------------------------
                # Relative orientation
                # ----------------------------------

                angle = (
                    ori[yy,xx]
                    -
                    kp_angle
                ) % 360

                ori_bin = (
                    angle / 45.0
                )

                magnitude = mag[
                    yy,
                    xx
                ]

                # ----------------------------------
                # Row interpolation
                # ----------------------------------

                r0 = int(
                    np.floor(row_bin)
                )

                r1 = r0 + 1

                wr1 = (
                    row_bin - r0
                )

                wr0 = (
                    1 - wr1
                )

                # ----------------------------------
                # Column interpolation
                # ----------------------------------

                c0 = int(
                    np.floor(col_bin)
                )

                c1 = c0 + 1

                wc1 = (
                    col_bin - c0
                )

                wc0 = (
                    1 - wc1
                )

                # ----------------------------------
                # Orientation interpolation
                # ----------------------------------

                o0 = int(
                    np.floor(ori_bin)
                ) % 8

                o1 = (
                    o0 + 1
                ) % 8

                wo1 = (
                    ori_bin
                    -
                    np.floor(
                        ori_bin
                    )
                )

                wo0 = (
                    1 - wo1
                )

                # ----------------------------------
                # Trilinear interpolation
                # ----------------------------------

                for r, wr in [
                    (r0,wr0),
                    (r1,wr1)
                ]:

                    if not (
                        0 <= r < 4
                    ):
                        continue

                    for c, wc in [
                        (c0,wc0),
                        (c1,wc1)
                    ]:

                        if not (
                            0 <= c < 4
                        ):
                            continue

                        descriptor[
                            r,
                            c,
                            o0
                        ] += (
                            magnitude
                            *
                            wr
                            *
                            wc
                            *
                            wo0
                        )

                        descriptor[
                            r,
                            c,
                            o1
                        ] += (
                            magnitude
                            *
                            wr
                            *
                            wc
                            *
                            wo1
                        )

        # ----------------------------------
        # Flatten
        # ----------------------------------

        descriptor = descriptor.flatten()

        # ----------------------------------
        # Normalize
        # ----------------------------------

        norm = np.linalg.norm(
            descriptor
        )

        if norm > 1e-7:

            descriptor /= norm

            descriptor = np.clip(
                descriptor,
                0,
                0.2
            )

            descriptor /= (
                np.linalg.norm(
                    descriptor
                )
                +
                1e-7
            )

        descriptors.append(
            descriptor
        )

        valid_keypoints.append(
            (
                x,
                y,
                octave,
                scale,
                kp_angle
            )
        )

    return (
        valid_keypoints,
        np.array(descriptors)
    )

kp1_desc, desc1 = generate_descriptors(
    oriented_kps,
    mag_pyr,
    ori_pyr
)

print(
    len(kp1_desc)
)

print(
    desc1.shape
)

print(desc1.shape)

"""Image

↓

Gaussian Pyramid

↓

DoG Pyramid

↓

Extrema Detection

↓

Contrast Filter

↓

Edge Filter

↓

NMS

↓

Multi-Orientation Assignment

↓

Trilinear Descriptor


Extrema             : 6563,
After Contrast      : 3181,
After Edge          : 1659,
After NMS           : 738,
After Orientation   : 1057,
Descriptors         : (1057,128),
"""

















